language: java
script: ./gradlew build jacocoTestReport --info
before_install:
  - chmod +x gradlew
jdk:
  - oraclejdk8
env:
  matrix:
  - TERM=dumb
after_success:
  - ./gradlew jacocoRootReport coveralls
